### ISSUE TITLE
구글 로그인 구현

### ISSUE THREAD

**Issue by seohyun1119** [jm83-database/Playdata-H.AI#10]
### requirements
```python
ultralytics==8.0.99
opencv-python==4.7.0.72
flask==2.3.2
Flask-WTF==1.1.1
Flask-Login==0.6.2
oauthlib==3.2.2
cryptography==41.0.2
pyOpenSSL==23.2.0
```

**Comment by seohyun1119** [comment]
### todo
- [x] URL 매핑할 거 만들기
- [x] 해당되는 템플릿 파일 HTML로 만들기 (와이어프레임 참고)
- [x] app.py와 main.py 합치기

**Comment by seohyun1119** [comment]
127.0.0.1 > localhost

**Comment by seohyun1119** [comment]
http => port 80
https => port 443
https가 보안이 더 좋으므로 https 사용

**Comment by seohyun1119** [comment]
포트: 한 서비스 당 유일한 값을 가짐
포트 맞춰주기 (5500)

**Comment by seohyun1119** [comment]
```python
python app.py
```

**Comment by seohyun1119** [comment]
host:port/path -> route는 '/path'를 불러오는 것!
HTTP Method: GET, POST, DELETE
